services:
  postgres:
    container_name: nasa-pictures-db
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_DB=nasa_pictures
      - POSTGRES_PASSWORD=root
    networks:
      - nasa-pictures-stealer-network
    volumes:
      - data:/var/lib/postgresql/data


  nasa-stealer-app:
    image: bitnami/java:17-debian-11
    container_name: nasa-pictures-stealer
    environment:
      DB_URL: jdbc:postgresql://localhost:5432/nasa_pictures
      DB_USERNAME: root
      DB_PASSWORD: root
      NASA_API_KEY: 9D53SLTqTGN8gnIvgbgcADsmekKq1bL0zyhWzs8R
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    command: [ "java", "-jar", "/app.jar" ]
    volumes:
      - ../build/libs/nasa-pictures-stealer-0.0.1-SNAPSHOT.jar:/app.jar
    networks:
      - nasa-pictures-stealer-network

networks:
  nasa-pictures-stealer-network:
    driver: bridge

volumes:
  data: